steps:
  # 1. Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']

  # 2. Build for production
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'API_KEY=$_API_KEY'

  # 3. Deploy to GCS Bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-d', 'dist', 'gs://${_BUCKET_NAME}/']

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
substitutions:
  _API_KEY: 'REPLACE_WITH_VALID_API_KEY_IN_GCP_CONSOLE'
  _BUCKET_NAME: 'social-service-map-ukraine-deploy'